[package]
name = "accents"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
regex = "1.10"
log = "0.4"
ron = { version = "0.8", optional = true }
serde = { version = "1", features = ["derive"], optional = true }

[features]
default = ["ron"]
ron = ["deserialize", "dep:ron"]
deserialize = ["dep:serde"]

[profile.dev]
opt-level = 3
