[package]
name = "pink_accents"
version = "0.0.1"
authors = ["fogapod"]
edition = "2021"
description = "Accent system based on string pattern matching"
license = "AGPL-3.0"
exclude = ["/.github", "/examples/accents", "/tests/sample_text.txt"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
regex = "1.10"
log = "0.4"
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
ron = { version = "0.8" }

[features]
default = ["deserialize"]
deserialize = ["dep:serde"]

[profile.dev]
opt-level = 3
