[package]
name = "pink_accents"
version = "0.0.3"
authors = ["fogapod"]
edition = "2021"
description = "Replacement of patterns in string to simulate speech accents"
repository = "https://github.com/Fogapod/pink_accents"
homepage = "https://github.com/Fogapod/pink_accents"
license = "AGPL-3.0"
keywords = ["text"]
categories = ["text-processing"]
exclude = [
    "/.github",
    "/examples",
    "/tests/sample_text.txt",
]

[dependencies]
rand = "0.8"
regex = "1.10"
log = "0.4"
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
ron = { version = "0.8" }
criterion = { version = "0.4", features = ["html_reports"] }

[features]
default = ["deserialize"]
deserialize = ["dep:serde"]

[profile.dev]
opt-level = 3

[[bench]]
name = "accents"
harness = false
